name: Release

on:
    # Allows running this workflow from other workflows
    workflow_call:
        inputs:
            tagged:
                default: false
                required: false
                type: boolean

jobs:
    release:
        runs-on: ubuntu-latest
        steps:
            - name: Download binaries
              uses: actions/download-artifact@v4
              with:
                  path: |
                      bin/
            - name: Create Release with pushed tag
              if: ${{ inputs.tagged }}
              uses: "marvinpinto/action-automatic-releases@latest"
              with:
                  repo_token: "${{ secrets.GITHUB_TOKEN }}"
                  prerelease: false
                  files: |
                      bin/ytgo-*/ytgo-*
            - name: Create Release with latest tag
              if: ${{ ! inputs.tagged }}
              uses: "marvinpinto/action-automatic-releases@latest"
              with:
                  automatic_release_tag: latest
                  repo_token: "${{ secrets.GITHUB_TOKEN }}"
                  prerelease: false
                  files: |
                      bin/ytgo-*/ytgo-*
